name: Rebase check

on: push

jobs:
  rebase-check:
    runs-on: ubuntu-latest
    env:
      AUTH: 'Authorization: token ${{ github.token }}'

    steps:
      - name: On push to master, invalidate all open pull requests
        if: github.ref == 'refs/heads/master'
        env:
          DATA: '{"state":"error","description":"please rebase", "context": "master updated"}'
        run: |
          curl -s -H "$AUTH" 'https://api.github.com/repos/${{ github.repository }}/pulls?state=open' |\
          jq -r '.[] | .statuses_url' |\
          while read url
          do
            echo "setting failed state on $url"
            curl -s -X POST -H "$AUTH" "$url" -d "${DATA}"
          done

      - name: On push to branch, check if not behind master
        if: github.ref != 'refs/heads/master' && !startsWith(github.ref, 'refs/tags')
        run: |
          BEHIND=`curl -s -H "$AUTH" https://api.github.com/repos/${{ github.repository }}/compare/master...${{ github.ref }} | jq -r '.behind_by'`
          if [ $BEHIND -gt 0 ]
          then
            echo "Branch is $BEHIND commits behind master, please rebase"
            exit 1
          fi
